"""add_password_hash_to_users

Revision ID: 5898d32bea95
Revises: c62d76806248
Create Date: 2026-02-21 23:25:19.470732

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from src.infrastructure.db.models.types.user import PasswordType

# revision identifiers, used by Alembic.
revision: str = "5898d32bea95"
down_revision: str | Sequence[str] | None = "c62d76806248"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password_hash", PasswordType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
