export const en = {
    navPatients: 'Patients',
    navHistory: 'History',
    demoDisclaimerTitle: 'Demo Disclaimer:',
    demoDisclaimerText: 'This application is for demonstration purposes only. Not intended for actual medical use.',
    currentMode: 'Current mode:',

    patientsTitle: 'Patients',
    patientsOnFile: (count: number) => `${count} patient${count !== 1 ? 's' : ''} on file`,
    cancel: 'Cancel',
    addPatient: 'Add patient',
    resetDemoData: 'Reset demo data',
    fullName: 'Full name',
    ageOptional: 'Age (optional)',
    add: 'Add',
    searchPlaceholder: 'Search by name or symptoms…',
    sortLastUpdated: 'Last updated',
    sortNameAZ: 'Name A→Z',
    sortMostWarnings: 'Most warnings',
    noPatientsTitle: 'No patients yet.',
    noPatientsDesc: 'Add a patient or click "Reset demo data" to seed examples.',
    noResultsTitle: (query: string) => `No results for "${query}"`,
    noResultsDesc: 'Try a different name or symptom keyword.',
    gettingStartedTitle: '👋 Getting started',
    gsStep1Title: '1. Select a patient',
    gsStep1Desc: ' — click "Open chat" on any card below.',
    gsStep2Title: '2. Enter symptoms',
    gsStep2Desc: ' — describe the chief complaint and run an assessment.',
    gsStep3Title: '3. Compare dynamics',
    gsStep3Desc: ' — use the compare panel to track changes across visits.',
    dismiss: 'Dismiss',

    historyTitle: 'History',
    prevDiagnoses: 'Previous diagnoses.',
    clearHistory: 'Clear history',
    clearConfirm: 'Clear all history? This cannot be undone.',
    historyCorrupt: 'History data was corrupt and has been reset.',
    readyToCompare: 'Ready to compare.',
    selectOneMoreToCompare: 'Select one more to compare.',
    compare: 'Compare',
    recentAnalyses: 'Recent Analyses',
    noHistoryTitle: 'No history available yet.',
    noHistoryDesc: 'Once you run a diagnosis, it will appear here.',
    view: 'View',
    rerun: 'Rerun',
    errorWord: 'error',

    diagnosisResult: 'Diagnosis Result',
    loading: 'Loading…',
    resultNotFound: 'Result not found.',
    idWord: 'ID',
    notFoundDesc: 'was not found in localStorage. It may have been cleared.',
    backToHistory: '← Back to History',
    traceId: 'trace_id:',
    shortLevel: 'Short',
    detailedLevel: 'Detailed',
    exportReport: 'Export report',
    arrowHistory: '← History',
    runEndedWithError: 'This run ended with an error',
    symptoms: 'Symptoms',
    diagnosesHeading: 'Diagnoses',
    noParsedDiagnoses: 'No parsed diagnoses available. Raw response shown below for debugging.',
    showRaw: 'Show raw response',
    hideRaw: 'Hide raw response',
    noData: 'No diagnosis data available for this run.',

    modeDemo: 'Demo',
    modeFallback: 'Fallback',
    modeLive: 'Live',

    navLogin: 'Login',
    navProfile: 'Profile',
    logout: 'Logout',
    loginTitle: 'Welcome Back',
    email: 'Email',
    password: 'Password',
    loginButton: 'Login',
    noAccount: "Don't have an account?",
    registerLink: 'Register',
    registerTitle: 'Create Account',
    confirmPassword: 'Confirm Password',
    registerButton: 'Create Account',
    hasAccount: 'Already have an account?',
    loginLink: 'Login here',
    doctorProfile: 'Doctor Profile',
    specialty: 'Specialty',
    save: 'Save',
    editProfile: 'Edit Profile',
    invalidEmail: 'Invalid email format.',
    passwordTooShort: 'Password must be at least 8 characters.',
    passwordsDoNotMatch: 'Passwords do not match.',
};
