export const ru = {
    navPatients: 'Пациенты',
    navHistory: 'История',
    demoDisclaimerTitle: 'Демо-версия:',
    demoDisclaimerText: 'Это приложение предназначено только для демонстрации. Не для реального медицинского использования.',
    currentMode: 'Текущий режим:',

    patientsTitle: 'Пациенты',
    patientsOnFile: (count: number) => {
        const rules = new Intl.PluralRules('ru-RU');
        const res = rules.select(count);
        let word = 'пациентов';
        if (res === 'one') word = 'пациент';
        if (res === 'few') word = 'пациента';
        return `${count} ${word} в базе`;
    },
    cancel: 'Отмена',
    addPatient: 'Добавить пациента',
    resetDemoData: 'Сбросить демо-данные',
    fullName: 'ФИО',
    ageOptional: 'Возраст (необязательно)',
    add: 'Добавить',
    searchPlaceholder: 'Поиск по имени или симптомам…',
    sortLastUpdated: 'Последние обновления',
    sortNameAZ: 'Имя А→Я',
    sortMostWarnings: 'Больше всего предупреждений',
    noPatientsTitle: 'Пока нет пациентов.',
    noPatientsDesc: 'Добавьте пациента или нажмите «Сбросить демо-данные» для загрузки примеров.',
    noResultsTitle: (query: string) => `Нет результатов для «${query}»`,
    noResultsDesc: 'Попробуйте другое имя или ключевое слово симптома.',
    gettingStartedTitle: '👋 С чего начать',
    gsStep1Title: '1. Выберите пациента',
    gsStep1Desc: ' — нажмите «Открыть чат» на любой карточке ниже.',
    gsStep2Title: '2. Введите симптомы',
    gsStep2Desc: ' — опишите основные жалобы и запустите анализ.',
    gsStep3Title: '3. Сравните динамику',
    gsStep3Desc: ' — используйте панель сравнения для отслеживания изменений.',
    dismiss: 'Скрыть',

    historyTitle: 'История',
    prevDiagnoses: 'Предыдущие диагнозы.',
    clearHistory: 'Очистить историю',
    clearConfirm: 'Очистить всю историю? Это действие нельзя отменить.',
    historyCorrupt: 'Данные истории были повреждены и сброшены.',
    readyToCompare: 'Готово к сравнению.',
    selectOneMoreToCompare: 'Выберите еще один для сравнения.',
    compare: 'Сравнить',
    recentAnalyses: 'Недавние анализы',
    noHistoryTitle: 'История пока пуста.',
    noHistoryDesc: 'Как только вы запустите диагностику, она появится здесь.',
    view: 'Смотреть',
    rerun: 'Перезапустить',
    errorWord: 'ошибка',

    diagnosisResult: 'Результат диагностики',
    loading: 'Загрузка…',
    resultNotFound: 'Результат не найден.',
    idWord: 'ID',
    notFoundDesc: 'не найден в localStorage. Возможно, он был удален.',
    backToHistory: '← Вернуться к истории',
    traceId: 'trace_id:',
    shortLevel: 'Кратко',
    detailedLevel: 'Подробно',
    exportReport: 'Экспорт отчета',
    arrowHistory: '← История',
    runEndedWithError: 'Этот запуск завершился с ошибкой',
    symptoms: 'Симптомы',
    diagnosesHeading: 'Диагнозы',
    noParsedDiagnoses: 'Нет распознанных диагнозов. Ниже показан сырой ответ для отладки.',
    showRaw: 'Показать сырой ответ',
    hideRaw: 'Скрыть сырой ответ',
    noData: 'Для этого запуска нет данных диагностики.',

    modeDemo: 'Демо',
    modeFallback: 'Fallback',
    modeLive: 'Live',

    navLogin: 'Войти',
    navProfile: 'Профиль',
    logout: 'Выйти',
    loginTitle: 'С возвращением',
    email: 'Email',
    password: 'Пароль',
    loginButton: 'Войти',
    noAccount: 'Нет аккаунта?',
    registerLink: 'Зарегистрироваться',
    registerTitle: 'Создать аккаунт',
    confirmPassword: 'Подтвердите пароль',
    registerButton: 'Создать аккаунт',
    hasAccount: 'Уже есть аккаунт?',
    loginLink: 'Войти здесь',
    doctorProfile: 'Профиль врача',
    specialty: 'Специальность',
    save: 'Сохранить',
    editProfile: 'Редактировать профиль',
    invalidEmail: 'Неверный формат email.',
    passwordTooShort: 'Пароль должен содержать минимум 8 символов.',
    passwordsDoNotMatch: 'Пароли не совпадают.',
};
